-- Optional sample data for local development/demo purposes.
-- Passwords are not seeded here since hashes are generated by the API
-- (PBKDF2 with a per-user salt) — register through the app instead of
-- inserting rows by hand.

USE TaskManagerDb;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.Users WHERE Email = 'demo@example.com')
BEGIN
    PRINT 'Register the demo user through the API (POST /api/auth/register) so the password hash is generated correctly.';
END
GO
